[package]
authors = ["manuel.r.puentes.d@gmail.com"]
edition = "2018"
name = "invitation"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "invitations"

[dependencies]
serde = "1"
hdk = "0.0.100"
derive_more = "0"

