[package]
name = "invitation_coordinator"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "invitation_coordinator"

[dependencies]
hdk = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
invitation_integrity = { workspace = true } 
